- name: Launch database
  docker_container:
    name: tp-database
    image: amartechnonv/tp-devops-database
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db

    networks:
      - name: tp_net
